lab_view/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, RegisterView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('lab/', include('labs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('admin/', admin.site.urls),
]

labs/urls.py
from django.urls import path
from .views import LabView, RackView

urlpatterns = [
    path('<int:pk>/', LabView.as_view(), name='lab'),
    path('rack/<int:pk>/', RackView.as_view(), name='rack')
]

labs/models.py
from django.db import models
from django.contrib.auth.models import User


class Lab(models.Model):
    """
    Representation of a lab environment.
    May contain any number of racks, which
    may contain any number of servers
    """
    name = models.CharField(max_length=200)
    nickname = models.CharField(max_length=20)
    rows = models.SmallIntegerField(default=1)
    authorized = models.ManyToManyField(User)

    def __str__(self):
        return self.name


class Rack(models.Model):
    """
    Representation of a server rack.
    May contain any number of servers. KVM is
    optional, link will not show up if null.
    Connected to Lab via foreign key.
    """
    name = models.CharField(max_length=200)
    nickname = models.CharField(max_length=20)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    row = models.SmallIntegerField(default=1)
    order = models.SmallIntegerField(default=1)
    kvm = models.URLField(null=True, blank=True)
    color = models.CharField(max_length=30, blank=True, null=True)
    dark = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Server(models.Model):
    """
    Representation of a server.
    Connected to Rack via foreign key.
    """
    name = models.CharField(max_length=200)
    nickname = models.CharField(max_length=20)
    rack = models.ForeignKey(Rack, on_delete=models.CASCADE)
    order = models.SmallIntegerField(default=1)
    size = models.SmallIntegerField(default=1)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-order']

lab_view/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views import generic
from labs.models import Lab


class HomeView(generic.TemplateView):
    """
    Home view with basic information
    """
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['labs'] = Lab.objects.order_by('-name')
        return context


class RegisterView(SuccessMessageMixin, generic.CreateView):
    """
    Registration view for new users
    """
    template_name = 'registration/register.html'
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    success_message = '%(username)s was created successfully. Please log in.'

labs/views.py
from django.views import generic
from .models import Lab, Rack, Server


class LabView(generic.DetailView):
    model = Lab

    template_name = 'labs/lab.html'


class RackView(generic.DetailView):
    model = Rack

    template_name = 'labs/rack.html'

labs/templates/labs/lab.html
{% extends 'base.html' %}
{% load range %}


{% block title %}{{ object.name }} | {% endblock %}


{% block content %}
  <v-container>
    <v-card class="mx-auto mt-12">
      <v-card-title class="text-h4">{{ object.name }}</v-card-title>
      <v-card-text class="text-body-1">
        <div style="display: grid;grid-auto-columns: 1fr;">
          {% for rack in object.rack_set.all %}
            <v-card
              :dark="{{ rack.dark|yesno:'true,false' }}"
              color="{{ rack.color|default:'grey lighten-4' }}"
              style="grid-column: {{ rack.row }} / span 1;grid-row: {{ rack.order }} / span 1;"
              class="ma-2"
            >
              <v-card-title class="text-h5">{{ rack.nickname }}</v-card-title>
              <v-card-subtitle class="text-subtitle-1">{{ rack.name }}</v-card-subtitle>
              <v-card-text class="text-body-1">
                <v-row>
                  <v-col cols="6">
                    {% if rack.kvm %}
                      <v-btn color="info" href="{{ rack.kvm }}" target="_blank">KVM</v-btn>
                    {% endif %}
                  </v-col>
                  <v-col cols="6">
                    {% if rack.server_set.all|length > 0 %}
                      <v-btn color="info" href="{% url 'rack' rack.id %}" target="_blank">Servers</v-btn>
                    {% endif %}
                  </v-col>
                </v-row>
              </v-card-text>
            </v-card>
          {% endfor %}
        </div>
      </v-card-text>
    </v-card>
  </v-container>
{% endblock %}

labs/templates/labs/rack.html
{% extends 'base.html' %}
{% load range %}


{% block title %}{{ object.name }} | {% endblock %}


{% block content %}
  <v-container>
    <v-card class="mx-auto mt-12 mb-16" max-width="600">
      <v-card-title class="text-h4">{{ object.name }}</v-card-title>
      <v-card-text class="text-body-1">
        <div class="rack-grid">
          {% for server in object.server_set.all %}
            <v-card
              color="grey"
              style="grid-column: 2; grid-row: -{{ server.order }} / span {{ server.size }}"
            >
              <v-card-title class="text-h5">{{ server.name }}</v-card-title>
            </v-card>
          {% endfor %}
          {% for num in 42|getrange %}
            {% if num != 0 %}
              <span style="grid-column: 1; grid-row: -{{ num }}; background-color: {% cycle 'grey' 'lightgrey' %};" class="text-center font-weight-bold pt-3">{{ num }}</span>
              <span style="grid-column: 3; grid-row: -{{ num }}; background-color: {% cycle 'grey' 'lightgrey' %};" class="text-center font-weight-bold pt-3">{{ num }}</span>
            {% endif %}
          {% endfor %}
        </div>
      </v-card-text>
    </v-card>
  </v-container>
{% endblock %}

templates/app-bar.html
{% load static gravatar %}


<v-app-bar app color="#0071c5">
  <v-toolbar-title class="font-weight-bold white--text mr-3">Lab View</v-toolbar-title>
  <v-toolbar-items>
    <v-btn text dark href="/">Home</v-btn>
  </v-toolbar-items>
  <v-spacer></v-spacer>
  {% if user.is_authenticated %}
    {% if user_labs %}
      <v-toolbar-items>
      {% for lab in user_labs %}
        <v-btn href="{% url 'lab' lab.id %}" text color="white">{{ lab.nickname }}</v-btn>
      {% endfor %}
      </v-toolbar-items>
      <v-divider vertical dark class="ml-3 mr-6"></v-divider>
    {% endif %}
    <v-menu offset-y>
      <template v-slot:activator="{ on }">
        <v-btn icon class="mr-2" v-on="on">
          <v-avatar>
            {% if user.email %}
              <v-img src="{{ user.email|gravatar }}"></v-img>
            {% else %}
              <v-img src="https://www.gravatar.com/avatar/1?d=mp"></v-img>
            {% endif %}
          </v-avatar>
        </v-btn>
      </template>
      <v-list>
        <v-subheader>Welcome, {{ user.username }}</v-subheader>
        {% if user.is_staff %}
        <v-list-item href="/admin" color="info">
          <v-list-item-title><span class="info--text font-weight-bold">Admin Panel</span></v-list-item-title>
        </v-list-item>
        <v-divider></v-divider>
        {% endif %}
        <v-list-item href="{% url 'logout' %}" color="error">
          <v-list-item-title><span class="error--text">Log Out</span></v-list-item-title>
        </v-list-item>
      </v-list>
    </v-menu>
  {% else %}
    <v-toolbar-items>
      <v-btn href="{% url 'login' %}" text color="white">Login</v-btn>
      <v-btn text color="yellow" href="{% url 'register' %}">Register</v-btn>
    </v-toolbar-items>
  {% endif %}
</v-app-bar>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
  <title>{% block title %}{% endblock title %}Lab View</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@5/css/materialdesignicons.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vuetify@2/dist/vuetify.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vue-snotify@3.2.1/styles/dark.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block additional_css %}{% endblock %}
</head>
<body>
  <div id="app" v-cloak>
    <v-app>
      {% include "app-bar.html" %}

      <v-main>
        {% block content %}{% endblock %}
        <vue-snotify></vue-snotify>
      </v-main>

      {% include "footer.html" %}
    </v-app>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vuetify@2/dist/vuetify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-resource@1/dist/vue-resource.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue-snotify@3/vue-snotify.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  {% block additional_vue_scripts %}{% endblock %}
  <script>
    let None = null;
    {% block vue_use %}{% endblock %}
    var app = new Vue({
      delimiters: ['[[', ']]'],
      el: '#app',
      vuetify: new Vuetify(),
      data: {% block data %}{}{% endblock %},
      props: {% block props %}{}{% endblock %},
      methods: {% block methods %}{}{% endblock %},
      watch: {% block watch %}{}{% endblock %},
      computed: {% block computed %}{}{% endblock %},
      mounted() {
        {% if messages %}
          {% for message in messages %}
            this.$snotify.{{ message.level_tag }}("{{ message|safe }}", "{{ message.tags|title }}", {timeout: 5000}){% if not forloop.last %},{% endif %}
          {% endfor %}
        {% endif %}
        {% block mounted %}{% endblock %}
      },
      created() {% block created %}{}{% endblock %},
      filters: {% block filters %}{}{% endblock %}
    });
  </script>
  {% block additional_scripts %}{% endblock %}
</body>
</html>

templates/footer.html
<v-footer padless fixed>
  <v-card flat tile width="100%" color="#0071c5">
    <v-card-text class="d-flex justify-space-between white--text">
      <span>Copyright &copy; 2020 Robert Jauss</span>
      <span>For use by anybody idgaf really</span>
    </v-card-text>
  </v-card>
</v-footer>

templates/home.html
{% extends 'base.html' %}


{% block content %}
  <v-container>
    <h1 class="text-h2 text-center my-12">Welcome to Lab View</h1>
    <p class="text-body-1 text-center">To get started, please log in or create an account, then request access to one
    of the following labs from your supervisor.</p>

    <v-card max-width="500" class="mx-auto mt-12">
      <v-list>
        <v-subheader>All labs</v-subheader>
        {% for lab in labs %}
          <v-list-item>
            <v-list-item-content>
              <v-list-item-title>{{ lab.name }}</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
        {% empty %}
          <v-list-item>
            <v-list-item-content>
              <v-list-item-title>No labs! Add one to get started</v-list-item-title>
            </v-list-item-content>
          </v-list-item>
        {% endfor %}
      </v-list>
    </v-card>

  </v-container>
{% endblock %}